# Application Browser
browser = chrome

#Application URL
url = https://www.demoblaze.com/

#uUser Details
username = vinoth.kannan
password = 123445
screenshotPath=.//screenshots//

name = Vinoth
country = India
city = Madurai
card = 12345678
month = 07
year = 2026